---
title: "GoalSelection"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(psych)
```

```{r dataframe}
goalratings <- read_spss("TransposedGoals.sav")
```

## assessing inter-rater agreement

```{r rater-agreement}

ICC(goalratings)

```


## Scatterplot of Goal Ratings

```{r scatterplot}
#avg. rating for dishonesty x avg. rating for honesty

goalratings <- goalratings %>%
  mutate(init_S2goals = if_else(Diff_Likelihood >= -1.43 & Diff_Likelihood <= 2.14, "Study 2", "Study 3"))

ggplot(data = goalratings,
       mapping = aes(x = Avg_DisLikelihood, y = Avg_HonLikelihood, color = init_S2goals)) +
  geom_point() +
  labs(title = "Scatterplot of Goal Ratings", x = "Dishonesty Likelihood", y = "Honesty Likelihood", color = "Goals")
```

## Filtering Goals That Pull In Both Directions


```{r filtering}
goalratings %>%
  arrange(desc(Diff_Likelihood))

goalratings %>%
  arrange(desc(Avg_DisLikelihood))

#filter the middle 50% of goals based on difference scores. This will reveal the 50% of goals that, on average, are rated to be similarly likely to be achieved by honesty and dishonesty.

#among those middle 50%, filter for those with above 2.8 and 3 avg. honesty/dishonesty likelihood ratings.

goalratings <- goalratings %>%
  filter(Diff_Likelihood <= 2.14) %>%
  filter(Diff_Likelihood >= -1.43) %>%
  filter(Avg_HonLikelihood > 2.8) %>%
  filter(Avg_DisLikelihood > 3)

goalratings %>%
  arrange(Diff_Likelihood)
```


```{r more-selective-filter}

goalratings <- goalratings %>%
  filter(Diff_Likelihood <= 2.14) %>%
  filter(Diff_Likelihood >= -1.43) %>%
  filter(Avg_HonLikelihood > 3) %>%
  filter(Avg_DisLikelihood > 3.2)

goalratings %>%
  arrange(Diff_Likelihood)


```



```{r}
skimr::skim(TransposedGoals)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
